# Generated by Django 5.0.1 on 2025-06-08 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0004_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapp.category'),
        ),
    ]
